### ISSUE TITLE
Performance drop when using dpdk with i40e.

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#26]
I'm using X710 (i40e) and testing libtrace 3.22 latest version.

The rx traffic is 8Gbps, but libtrace 3.22 with dpdk only handles about 70% packets.
When I use dpdk pktgen to check rx performance, there is no packet drop.

So I look into the format_dpdk.c and found the difference in queue_setup.
libtrace use rx_conf = {pth=8,hth=8,wth=4,freeth=0} but
pktgen uses NULL, which means default rx_conf={8,8,0,32}. (from i40e_ethdev.h)

After I changed queue_setup(...,&rx_conf,...) to queue_setup(...,NULL,...),
there is no drop any more.

Unless there is any other reason, using default for rx/tx queue setup seems better.

Tested on dpdk 1.8.0 and dpdk 2.0.0.
(It seems libtrace is working with dpdk 2.0.0, Hooray~)

**Comment by rsanger** [comment]
Thanks for reporting this, I have fixed it in develop, this should be included in the next official release.
Turns out pre 1.8 dpdk never supported this default hence why we did not use defaults.

Note: There are some significant performance improvements for the dpdk format included in the libtrace4 branch. I you are still having issues consider trying this branch, your existing code should work without modification. However we have not merged this patch into libtrace4 yet, so you might need to reapply this fix.
