### ISSUE TITLE
libtrace.a doesn't include wandio, dpdk implementation.

### ISSUE THREAD

**Issue by EaseTheWorld** [wanduow/libtrace#38]
I recently changed my application to use libtrace.a instead of libtrace.so.
but then I had to link libwandio.a and dpdk.a as well.

I thought libtrace.a includes all symbols from libwandio.a and libintel_dpdk.a.
$ nm libtrace.a | grep wandio -> shows 'U' not 'T'
$ nm libtrace.a | grep rte -> shows 'U' not 'T'

Is it usual for static library?
I'm not familiar with static link so please correct me if I'm wrong.

**Comment by salcock** [comment]
My thoughts are that it should be your responsibility to link against all of the dependencies if you take the static linking route. Libtrace can have a lot of dependencies and many of those dependencies can also have a lot of their own dependencies -- for instance, libwandio can depend on zlib, libbzip2, libcurl, liblzma etc. Creating a libtrace.a that includes all of the dependencies will result in a very large static library that duplicates many of the symbols on your system.

The libtrace.a that you are using only really exists as a by-product of the build process, rather than being something that we expect people to use. Is there a particular reason you need to use static linking over the standard dynamic linking?

**Comment by EaseTheWorld** [comment]
Ok I agree. I will link other static libs with it. The reason I use static
link is to deploy with one binary to linux-unfriendly-colleague. I will
think of other method like rpmbuild.
Please close this issue. Thx.

2016. 11. 25. 오전 6:52에 "Shane Alcock" <notifications@github.com>님이 작성:

My thoughts are that it should be your responsibility to link against all
of the dependencies if you take the static linking route. Libtrace can have
a lot of dependencies and many of those dependencies can also have a lot of
their own dependencies -- for instance, libwandio can depend on zlib,
libbzip2, libcurl, liblzma etc. Creating a libtrace.a that includes all of
the dependencies will result in a very large static library that duplicates
many of the symbols on your system.

The libtrace.a that you are using only really exists as a by-product of the
build process, rather than being something that we expect people to use. Is
there a particular reason you need to use static linking over the standard
dynamic linking?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/wanduow/libtrace/issues/38#issuecomment-262848675>, or mute
the thread
